# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Debug'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK' 
  inputs:
    version: 8.x
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    

# - task: NuGetCommand@2
#   inputs:
#     command: pack
#     packagesToPack: '**/*.csproj'
#     packDestination: '$(Build.ArtifactStagingDirectory)'
  

- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/DigiQuiz.WebAPI'
    targetFiles: '/**/appsettings.*.json'
    fileType: 'json'
    

- task: DotNetCoreCLI@2
  displayName: 'Tests'
  inputs:
    command: test
    projects: '**/DigiQuiz.UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'